# Problem 2 - Even Fibonacci numbers
# ================================
# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
#   1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.


MAX_NUMBER = 4000000


def main():
    return fib(1, 2) + 2


def fib(a, b):
    c = a + b
    return (c if c % 2 else 0) + fib(b, c) if c < MAX_NUMBER else 0


if __name__ == "__main__":
    print(main())
